### ISSUE TITLE
B971011 Multiple entries

### ISSUE THREAD

**Issue by bsul9430** [notionparallax/ShadowWolf#605] opened 2015-03-25 06:35 UTC
there are multiple P&P entries for B971011, including 2 of the same sub entries (systems analysis lab) putting all info

Put XX in front of the name to identify those to be deleted

**Comment by bsul9430** [comment] 2015-03-25 06:37
not sure what the XX S041205 is though.

**Comment by hinds89** [comment] 2015-08-20 00:00
CLOSE - This issue is a duplicate of #755

**Closed by hinds89** 2015-08-20 00:00 UTC
Labels: DB change
