### ISSUE TITLE
new key dates appear top but 'add' button is at bottom

### ISSUE THREAD

**Issue by Dawil** [notionparallax/ShadowWolf#668] opened 2015-06-16 07:18 UTC
this makes the workflow cumbersome

**Comment by Dawil** [comment] 2015-06-16 07:32
I'll move the button to the first instead of last element for editables.

**Comment by Dawil** [comment] 2015-06-16 07:43
New development: for anything that isn't a key date the new items appear at the bottom (because they aren't sorted) which is problematic.

**Comment by notionparallax** [comment] 2015-06-22 06:41
dupe of #455

**Closed** 2015-07-08 02:17 UTC
