### ISSUE TITLE
When creating a new Project in P&P Text Issues

### ISSUE THREAD

**Issue by bsul9430** [notionparallax/ShadowWolf#496] opened 2015-01-29 22:58 UTC
Created a new project in P&P and it won't let me add anything to the text tab, and i also cannot add in project categories in the summary tab

**Comment by bsul9430** [comment] 2015-01-29 23:05
Project B010707

**Comment by notionparallax** [comment] 2015-01-29 23:18
duplicate of #480

**Closed by notionparallax** 2015-01-29 23:18 UTC
